import Head from 'next/head'
import Header from '../components/header'
import { instance } from "../axios"
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router'

export default function Login() {

  const [email , setEmail ] = useState('')
  const [password , setPassword ] = useState('')
  const router = useRouter()

  const handleChangeEmail = (event) => {
    setEmail(event.target.value)
  }
  const handleChangePassword = (event) => {
    setPassword(event.target.value)
  }

  function login() {
    instance.post(`/login` , { username: email, password : password })
            .then(res => {
                console.log(res.data)
                if (typeof window !== 'undefined') {
                    window.localStorage.setItem("token", res.data.token);
                    if(res.data.admin == 1){
                      window.localStorage.setItem("admin" , "admin");
                    }
                    router.push("/dashboard")
                }
            })
            .catch(err => console.log(err))
  } 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">
        <div className="card">
            <h3 className='h3_login'>Login</h3>
            <div className="inputBox">
                <input type="text" required="required" value={email} onChange={handleChangeEmail}/>
                <span>Username</span>
            </div>

            <div className="inputBox">
                <input type="password" required="required" value={password} onChange={handleChangePassword}/>
                <span>Password</span>
            </div>

            <button onClick={login}>Enter</button>

        </div>
    </div>
    </div>
  )
}
