import Head from 'next/head'
import Header from '../components/header'
import { instance } from "../axios"
import { useState, useEffect } from 'react';
import Loading from '../components/loading';
import { useRouter } from 'next/router'

export default function Login() {
  const [data, setData] = useState(null)
  const [key, setKey] = useState(null)
  const [isLoading, setLoading] = useState(false)
  const [token, setToken] = useState(null)

  const [email , setEmail ] = useState('')
  const [password , setPassword ] = useState('')

  const handleChangeEmail = (event) => {
    setEmail(event.target.value)
  }
  const handleChangePassword = (event) => {
    setPassword(event.target.value)
  }

  useEffect(() => {
    setLoading(true)
    instance.get('/user').then(res => {
      setData(res.data)
      instance.get('/key').then(res => {
        setKey(res.data)
        setLoading(false)
      }).catch(err => console.log(err))
    }).catch(err => console.log(err))
    setLoading(true)


    setToken(localStorage.getItem("token"))
  }, [])
  if (isLoading) return <Loading />
  if (!data) return <Loading />

  function change(){
    
      instance.post(`/changepassword` , { ancienpass: email, newpass : password })
              .then(res => {
                  console.log(res.data)
                  
              })
              .catch(err => console.log(err))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Loading />
      <div className='container_victimes'>
        <div className='container_paylaod_dashboard'>
          <div className='paylaod_profile'>
            <div className='container_pseudo_profile'>
              <p>{data.username}</p>
              <p>-</p>
              <p>{data.cle}</p>
            </div>
            <p>La Key expire le : {key.expire}</p>
            <p>Your plan : {key.plan}</p>
            <p>Change password :</p>
            <div className='container_change_password'>
              
              <div className="inputBox">
                <input type="password" required="required" value={email} onChange={handleChangeEmail} />
                <span>old password</span>
              </div>

              <div className="inputBox">
                <input type="password" required="required" value={password} onChange={handleChangePassword} />
                <span>New password</span>
              </div>

              <button onClick={change}>Enter</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
