import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import Link from 'next/link'
import { instance } from "../axios"
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router'

export default function Signup() {

  const [email , setEmail ] = useState('')
  const [password , setPassword ] = useState('')
  const [key , setKey ] = useState('')
  const router = useRouter()

  const handleChangeEmail = (event) => {
    setEmail(event.target.value)
  }
  const handleChangePassword = (event) => {
    setPassword(event.target.value)
  }
  const handleChangeKey = (event) => {
    setKey(event.target.value)
  }

  function signup() {
    instance.post(`/signup` , { username: email, password : password, key: key })
            .then(res => {
              console.log(res.data)
              router.push("/login")
            })
            .catch(err => console.log(err))
  } 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div class="container">
        <div class="card_signup">
            <h3 className='h3_login'>Inscription</h3>
            <div class="inputBox">
                <input type="text" required="required" value={email} onChange={handleChangeEmail}/>
                <span>Username</span>
            </div>

            <div class="inputBox">
                <input type="password" required="required" value={password} onChange={handleChangePassword}/>
                <span>Password</span>
            </div>

            <div class="inputBox">
                <input type="password" required="required" value={key} onChange={handleChangeKey}/>
                <span>Key</span>
            </div>

            <button onClick={signup}>Enter</button>

        </div>
    </div>
    </div>
  )
}
