/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: yourejustjellyfish (https://sketchfab.com/yourejustjellyfish)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chocolate-chip-cookie-free-1f75786d2bf047a38f3971d7758aa990
title: Chocolate Chip Cookie ( FREE )
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cookie(props) {
  const { nodes, materials } = useGLTF('./cookie.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.01, -0.13, -0.42]} rotation={[1.57, -0.13, 0.18]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0.14, 0.4, -0.12]} rotation={[1.4, 0.67, -0.8]} scale={0.22}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./cookie.gltf')
