import Head from 'next/head'


export default function Loading() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <div class="loader">
            <div class="loader_spin"></div>
        </div>
      
        
    </div>
  )
}


